sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t onyx-docker .
  - docker run -d -p 127.0.0.1:8080:8080 --name onyx-docker onyx-docker

script:
  - docker ps | grep -q "onyx-docker"